apiVersion: v1
kind: Service
metadata:
  annotations:
    openyurt.io/topologyKeys: openyurt.io/nodepool
  name: device-rasp
spec:
  ports:
    - name: tcp
      port: 59996
      protocol: TCP
      targetPort: 59996
  selector:
    app: device-rasp

---
apiVersion: apps.openyurt.io/v1alpha1
kind: UnitedDeployment
metadata:
  name: device-rasp
spec:
  selector:
    matchLabels:
      app: device-rasp
  workloadTemplate:
    deploymentTemplate:
      metadata:
        labels:
          app: device-rasp
      spec:
        template:
          metadata:
            labels:
              app: device-rasp
          spec:
            hostname: device-raspberrypi
            containers:
              - name: device-raspberrypi
                hostname: device-raspberrypi
                image: huiwq1990/device-raspberrypi:v0.0.0-dev
                imagePullPolicy: Always
                env:
                  - name: SERVICE_HOST
                    value: device-raspberrypi
                envFrom:
                  - configMapRef:
                      name: common-variables
  topology:
    pools:
      - name: hangzhou
        nodeSelectorTerm:
          matchExpressions:
            - key: apps.openyurt.io/nodepool
              operator: In
              values:
                - hangzhou
        replicas: 1
        tolerations:
          - effect: NoSchedule
            key: apps.openyurt.io/example
            operator: Exists
