
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: consul
#spec:
#  rules:
#    - host: consul.edgex.epaas.domain
#      http:
#        paths:
#          - backend:
#              serviceName: edgex-core-consul
#              servicePort: 8500
#            path: /
#            pathType: Prefix

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: edgex-ui
spec:
  rules:
    - host: edgexui.openyurt.jdos.domain
      http:
        paths:
          - backend:
              service:
                name: edgex-ui-test
                port:
                  number: 4000
            path: /
            pathType: ImplementationSpecific

---
# 默认edgex-ui service会进行流量拓扑，这里先忽略
apiVersion: v1
kind: Service
metadata:
  name: edgex-ui-test
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: edgex-ui-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-ui-test
spec:
  selector:
    matchLabels:
      app: edgex-ui-test
  template:
    metadata:
      labels:
        app: edgex-ui-test
    spec:
      #      affinity:
      #        nodeAffinity:
      #          requiredDuringSchedulingIgnoredDuringExecution:
      #            nodeSelectorTerms:
      #              - matchExpressions:
      #                  - key: apps.openyurt.io/nodepool
      #                    operator: In
      #                    values:
      #                      - hangzhou
      containers:
        - env:
            - name: Service_Host
              value: edgex-ui
          envFrom:
            - configMapRef:
                name: common-variables
          image: nexus3.edgexfoundry.org:10004/edgex-ui:latest
          name: ui
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
      hostname: edgex-ui
      tolerations:
        - effect: NoSchedule
          operator: Exists

#curl -H 'Host: edgexui.openyurt.jdos.domain' 10.103.123.173

#curl 10.96.158.107:4000